<?php

return [
    'fiscal' => [
        'PENDIENTE' => [
            'label' => 'Pendiente de envio',
            'normalized' => 'PENDING',
            'group' => 'draft',
            'ui_class' => 'pendiente',
            'help' => 'La venta todavia no fue enviada al flujo de facturacion.',
        ],
        'RECEPCIONADA' => [
            'label' => 'En proceso',
            'normalized' => 'IN_PROGRESS',
            'group' => 'pending',
            'ui_class' => 'recepcionada',
            'help' => 'La venta fue enviada y sigue en proceso de confirmacion.',
        ],
        'PENDIENTE_CONFIRMACION' => [
            'label' => 'En proceso',
            'normalized' => 'IN_PROGRESS',
            'group' => 'pending',
            'ui_class' => 'recepcionada',
            'help' => 'La venta fue enviada y todavia esta en proceso de confirmacion.',
        ],
        'CONTINGENCIA_CREADA' => [
            'label' => 'Pendiente por contingencia',
            'normalized' => 'IN_PROGRESS',
            'group' => 'pending',
            'ui_class' => 'contingencia',
            'help' => 'La venta quedo pendiente por contingencia mientras se confirma con impuestos.',
        ],
        'PROCESADO' => [
            'label' => 'Facturada',
            'normalized' => 'BILLED',
            'group' => 'facturada',
            'ui_class' => 'procesado',
            'help' => 'La factura ya fue confirmada y esta lista para su uso.',
        ],
        'OBSERVADO' => [
            'label' => 'Observado',
            'normalized' => 'REJECTED',
            'group' => 'observada',
            'ui_class' => 'observado',
            'help' => 'La emision quedo observada y requiere revision antes de reenviar.',
        ],
        'ANULADA' => [
            'label' => 'Anulada',
            'normalized' => 'CANCELLED',
            'group' => 'anulada',
            'ui_class' => 'anulada',
            'help' => 'La factura fue anulada correctamente.',
        ],
        'ANULACION_SOLICITADA' => [
            'label' => 'Anulacion solicitada',
            'normalized' => 'CANCELLATION_PENDING',
            'group' => 'pending',
            'ui_class' => 'contingencia',
            'help' => 'La solicitud de anulacion fue enviada y espera notificacion final.',
        ],
        'ANULACION_OBSERVADA' => [
            'label' => 'Anulacion observada',
            'normalized' => 'REJECTED',
            'group' => 'observada',
            'ui_class' => 'observado',
            'help' => 'La solicitud de anulacion fue observada por SUFE.',
        ],
        'REGISTRADA_OFICIAL' => [
            'label' => 'Registrada sin facturacion',
            'normalized' => 'OFFICIAL',
            'group' => 'oficial',
            'ui_class' => 'recepcionada',
            'help' => 'La venta fue registrada como envio oficial y no genera factura electronica.',
        ],
        'DESCONOCIDO' => [
            'label' => 'Estado desconocido',
            'normalized' => 'UNKNOWN',
            'group' => 'unknown',
            'ui_class' => 'desconocido',
            'help' => 'No hay informacion suficiente para determinar el estado de la venta.',
        ],
    ],
    'cart' => [
        'FACTURADA' => [
            'label' => 'Facturada',
            'normalized' => 'BILLED',
            'group' => 'facturada',
            'ui_class' => 'procesado',
            'help' => 'El cobro ya fue facturado y ahora se trata como venta emitida.',
        ],
        'PENDIENTE' => [
            'label' => 'Pendiente',
            'normalized' => 'IN_PROGRESS',
            'group' => 'pending',
            'ui_class' => 'pendiente',
            'help' => 'La emision sigue pendiente de confirmacion.',
        ],
        'RECHAZADA' => [
            'label' => 'Rechazada',
            'normalized' => 'REJECTED',
            'group' => 'observada',
            'ui_class' => 'observado',
            'help' => 'La emision fue rechazada y requiere revision.',
        ],
        'ERROR' => [
            'label' => 'Error',
            'normalized' => 'ERROR',
            'group' => 'error',
            'ui_class' => 'observado',
            'help' => 'La emision encontro un error y requiere revision.',
        ],
        'NO_APLICA' => [
            'label' => 'No aplica',
            'normalized' => 'NOT_APPLICABLE',
            'group' => 'neutral',
            'ui_class' => 'recepcionada',
            'help' => 'No existe una emision fiscal aplicable para este cobro.',
        ],
        'DESCARTADA' => [
            'label' => 'Descartada',
            'normalized' => 'DISCARDED',
            'group' => 'discarded',
            'ui_class' => 'anulada',
            'help' => 'La transaccion fue descartada localmente y no debe tratarse como venta valida.',
        ],
        'QR_PENDIENTE' => [
            'label' => 'QR pendiente',
            'normalized' => 'QR_PENDING',
            'group' => 'qr_pendiente',
            'ui_class' => 'pendiente',
            'help' => 'El cobro QR sigue pendiente de pago.',
        ],
        'QR_PAGADO' => [
            'label' => 'Pagado QR',
            'normalized' => 'QR_PAID_UNBILLED',
            'group' => 'qr_pagado_sin_factura',
            'ui_class' => 'recepcionada',
            'help' => 'El cobro QR fue confirmado, pero todavia no fue facturado.',
        ],
        'QR_ANULADO' => [
            'label' => 'QR anulado',
            'normalized' => 'CANCELLED',
            'group' => 'qr_cancelado',
            'ui_class' => 'anulada',
            'help' => 'El intento de cobro QR fue cancelado o fallido.',
        ],
    ],
];
